# Generated by Django 6.0.4 on 2026-05-06 13:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['content', 'created_at', 'id'], name='comment_content_created_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['is_active', '-created_at', '-id'], name='content_active_feed_idx'),
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['content', 'reaction', 'is_active'], name='reaction_type_active_idx'),
        ),
    ]
